@startuml
'https://plantuml.com/sequence-diagram

!pragma layout smetana

package com.isep.controllers{
    abstract class ControlleurBase{

    }

    class MainControlleur{

    }

    class GameControlleur{
        }

     class PlayerCreationControlleur{
         }




    ControlleurBase <|-- MainControlleur
    ControlleurBase <|-- GameControlleur
    ControlleurBase <|-- PlayerCreationControlleur
}
package com.isep.game{

package com.isep.item{

    class VictoryPointsCard
    class Cat
    class ConflictToken
    class ProgressToken



    abstract Cards{}

    class MaterialCard extends Cards
    class ScienceCard extends Cards
    class WarCard extends Cards
    class PoliticCard extends Cards

   Wonders *-- WondersList
   WondersList *-- Cards



    enum WondersList {
    Gizeh
    Rhodes
    Babylone
    Ephese
    Halicarnasse
    Alexandrie
    Olympie
    }




}
    class Game{
    List<ConflictToken>
    }

    class MusicPlayer{
    }

    abstract Player{
    Wonders
    List<Cards>
    List<ProgressToken>
    VictoryPointsCard
    Cat
    }

    abstract Player
        class Human
        class Bot

    Game *-- Player
    Game *-- MusicPlayer

    Player *-- Bot
    Player *-- Human
  Game o- ControlleurBase

}


@enduml